# A linha 'version' foi removida, conforme a recomendação do Docker

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'wordpress_db'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: '123'
    networks:
      - wordpress_net

  wordpress:
    build: .
    container_name: wordpress_fpm
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'local'
      WORDPRESS_DB_PASSWORD: '123'
      WORDPRESS_DB_NAME: 'wordpress_db'
      WORDPRESS_TABLE_PREFIX: 'wp_'
      XDEBUG_MODE: 'debug'
    volumes:
      - ./wordpress:/var/www/html
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom-xdebug.ini
    networks:
      - wordpress_net

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
    driver: bridge
